name: Brownfields CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lincoln15/wethinkcode:0.0.3-snapshot

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile
        run: mvn -B compile

      - name: Test
        run: mvn -B test
